### ISSUE TITLE
Null pointer exception when selecting a path from the TR set

### ISSUE THREAD

**Issue by fcmartins** [pestt/PESTT#11]
1. Generate the graph for the following method
   
   public void ifThenWithInitialNode () {
       int x = 0;
       if (x == 0)
           x = 2;
   }
2. Select the complete Path coverage criteria
3. Activate link CFG with source code
4. Generate the TR
5. Select the first path [0, 1, 2, 3] in the TR

A null pointer exception error occurs

**Comment by pestt** [comment]
Problem fixed.
