### ISSUE TITLE
Coverage criteria nodes too wide

### ISSUE THREAD

**Issue by fcmartins** [pestt/PESTT#20]
At least in a MAC the nodes for the Graph Coverage Criteria are too wide, which makes it difficult to accomodate in a screen with low resolution like when using a beamer. For instance, CRTC, SRTC, CPC are quite wide.

**Comment by ruigameiro** [comment]
In fact the visual appearance of the plug-in (inexplicably) has some "problems" in the Mac OS.
Such "problems" do not happen on other OS.
The following figure demonstrates the appearance of the Graph Coverage Criteria view in Ubuntu.

![Image not Found](https://github.com/pestt/documents/blob/master/issues/Graph%20Coverage%20Criteria.jpg?raw=true)

We are working to fix this "problem" in Mac OS.

**Comment by ruigameiro** [comment]
The "problems" of visual appearance in the Mac OS have been fixed.
