### ISSUE TITLE
Code is not being painted correctly

### ISSUE THREAD

**Issue by fcmartins** [pestt/PESTT#23]
1. Generate a CFG graph, for instance, for the following method

/**
     \* @CoverageCriteria PRIME_PATH
     \* @InfeasiblePath [0, 1, 3]
     \* @AdditionalTestPath [0, 1, 2, 3]
     */
    public void ifThenWithInitialAndFinalNode () {
        int x = 0;
        if (x == 0)
            x = 2;
        System.out.println(x);
    }
1. activate the Link editor with graph visualizer.
2. check that either when selecting a test path or a requirement path, the code
   is colored correctly.
3. remove the infeasible mark for path 0, 1, 3
4. select one of the paths
5. confirm that the code is not being colored correctly.

**Comment by ruigameiro** [comment]
This problem was fixed.
