### ISSUE TITLE
Tour with detours

### ISSUE THREAD

**Issue by fcmartins** [pestt/PESTT#26]
For the following method and testPath, 
the Test Requirement [0, 4] should be covered.

 /**
     \* @CoverageCriteria PRIME_PATH
     \* @AdditionalTestPath [0, 1, 2, 5, 4]
     */
    public void nestedIfThenElse () {
        if (x == 0) {
            int y = 2;
            if (y % 2 == 0)
                System.out.println("par");
            else 
                System.out.println("impar");
        }
    }
[3/25/12 6:02:50 PM] fmartins: o tourWithDetours deveria cobrir o caminho 0, 4

**Comment by ruigameiro** [comment]
We made all necessary changes to fix that problem.
