### ISSUE TITLE
Incorrect handling of ! operator

### ISSUE THREAD

**Issue by edrdo** [pestt/PESTT#33]
The ! operator is not correctly handled in terms of def-use analysis. See attached screenshot: edge (1,2) -- corresponding to first if branch in code snippet ---
is marked as _defining_ x. 

``` java
  int foo(boolean x) {
    int r = 0;

    if (!x)
      r = 1;

    if (x == false)
      r = 1;

    return r;
  }
```

![Screen Shot 2013-03-03 at 5-1 26 18 PM](https://f.cloud.github.com/assets/1699245/290770/04f4b624-92f1-11e2-9860-97cc78a48673.png)

**Comment by Sokas** [comment]
Fixed!
~, + and - operators included.
